version: '3.8'
services:
  api:
    build: src
    restart: always
    ports:
      - '${HTTP_EXPRESS_PORT}:${HTTP_EXPRESS_PORT}'
      - '${HTTPS_EXPRESS_PORT}:${HTTPS_EXPRESS_PORT}'
    environment:
      - DB_HOST=mongodb
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - HTTP_EXPRESS_PORT=${HTTP_EXPRESS_PORT}
      - HTTPS_EXPRESS_PORT=${HTTPS_EXPRESS_PORT}
      - HTTPS=${HTTPS}
    volumes:
      - ./src:/app

volumes:
  db: