name: 'Tests and Coverage'

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DB_USER: ${{secrets.DB_USER}}
  DB_PASS: ${{secrets.DB_PASS}}
  DB_PORT: ${{vars.DB_PORT}}
  DB_HOST: ${{vars.DB_HOST}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
  Tests_and_Coverage:
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Tests and Coverage report
    steps:
      - uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-username: ${{secrets.DB_USER}}
          mongodb-password: ${{secrets.DB_PASS}}
          mongodb-db: test
          mongodb-port: ${{vars.DB_PORT}}

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test
          working-directory: src/